"use client";

import { achievementInputSchema, achievementMetrics, formatBRL, type Achievement, type AchievementInput, type AchievementMetric, type AdminAchievements, type AchievementRecipients } from "@aionix/shared";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ShoppingBasket, CalendarDays, Check, ChevronLeft, ChevronRight, Coins, Compass, Crown, Gift, Heart, Leaf, Pencil, Plus, Rocket, Sparkles, Star, Trophy, Users, X, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { api, qs } from "@/lib/api";
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Input, PageHeader, Select, Skeleton, Switch, Textarea } from "@/components/ui";

const categories = { first_steps: "Primeiros passos", shopping: "Compras", exploration: "Descobertas", loyalty: "Fidelidade", consistency: "Constância" };
const difficulties = { easy: "Fácil", medium: "Intermediária", hard: "Difícil", legendary: "Lendária" };
const icons: Record<AchievementInput["icon"], LucideIcon> = { sparkles: Sparkles, basket: ShoppingBasket, trophy: Trophy, heart: Heart, leaf: Leaf, gift: Gift, crown: Crown, star: Star, compass: Compass, calendar: CalendarDays, coins: Coins, rocket: Rocket };
const iconNames = { sparkles: "Brilho", basket: "Cesta", trophy: "Troféu", heart: "Coração", leaf: "Folha", gift: "Presente", crown: "Coroa", star: "Estrela", compass: "Bússola", calendar: "Calendário", coins: "Moedas", rocket: "Foguete" };
const colors = { amber: { name: "Âmbar", style: "bg-amber-100 text-amber-800" }, emerald: { name: "Esmeralda", style: "bg-emerald-100 text-emerald-800" }, sky: { name: "Azul", style: "bg-sky-100 text-sky-800" }, rose: { name: "Rosa", style: "bg-rose-100 text-rose-800" }, violet: { name: "Violeta", style: "bg-violet-100 text-violet-800" } };
const metrics: Record<AchievementMetric, { label: string; unit: string; help: string }> = {
  orders_count: { label: "Quantidade de compras", unit: "compras", help: "Conta pedidos entregues. Pedidos cancelados ou em andamento não contam." },
  single_spend: { label: "Valor em uma compra", unit: "R$", help: "Maior valor pago em produtos em um único pedido concluído (sem a taxa de entrega)." },
  total_spend: { label: "Valor acumulado em compras", unit: "R$", help: "Soma do valor pago em produtos nos pedidos concluídos (sem a taxa de entrega)." },
  distinct_products: { label: "Produtos diferentes", unit: "produtos", help: "Conta produtos distintos em pedidos entregues; repetir o mesmo produto não aumenta a meta." },
  distinct_categories: { label: "Categorias diferentes", unit: "categorias", help: "Conta categorias distintas dos produtos comprados em pedidos entregues." },
  redemptions_count: { label: "Prêmios resgatados", unit: "resgates", help: "Conta resgates de prêmios não cancelados do programa de fidelidade." },
  coins_earned: { label: "Moedas acumuladas", unit: "moedas", help: "Conta apenas moedas confirmadas de compras entregues. Bônus de conquistas não contam; gastar moedas não reduz o progresso." },
  shopping_days: { label: "Dias diferentes de compra", unit: "dias", help: "Conta as datas de criação dos pedidos entregues, no horário de Brasília. Os dias não precisam ser consecutivos." },
  shopping_months: { label: "Meses diferentes de compra", unit: "meses", help: "Conta os meses de criação dos pedidos entregues, no horário de Brasília. Os meses não precisam ser consecutivos." },
  profile_complete: { label: "Perfil completo", unit: "perfil", help: "Libera ao preencher nome, telefone e cadastrar um endereço. Meta fixa: 1." },
  pickup_count: { label: "Retiradas na loja", unit: "retiradas", help: "Conta pedidos retirados na loja e concluídos. Só aparece no app enquanto a retirada estiver ativa em Configurações; quem já conquistou mantém a medalha." },
};
const isMoney = (metric: AchievementMetric) => metric === "single_spend" || metric === "total_spend";
const number = (n: number) => n.toLocaleString("pt-BR");
const ruleLabel = (a: AchievementInput) => `${metrics[a.rule.metric].label}: ${isMoney(a.rule.metric) ? formatBRL(a.rule.target) : number(a.rule.target)}`;
function Medal({ achievement, large = false }: { achievement: Pick<AchievementInput, "icon" | "color">; large?: boolean }) {
  const Icon = icons[achievement.icon] ?? Trophy;
  return <span className={`grid shrink-0 place-items-center rounded-2xl ${large ? "size-20" : "size-12"} ${colors[achievement.color]?.style ?? colors.amber.style}`}><Icon strokeWidth={1.7} className={large ? "size-10" : "size-6"} aria-hidden /></span>;
}
const initial: AchievementInput = { slug: "", title: "", description: "", icon: "sparkles", color: "amber", category: "first_steps", difficulty: "easy", rule: { metric: "orders_count", target: 1 }, xp: 50, bonusCoins: 0, active: true, sortOrder: 100 };

function AchievementEditor({ item, onClose }: { item: Achievement | null; onClose: () => void }) {
  const [form, setForm] = useState<AchievementInput>(item ? { slug: item.slug, title: item.title, description: item.description, icon: item.icon, color: item.color, category: item.category, difficulty: item.difficulty, rule: item.rule, xp: item.xp, bonusCoins: item.bonusCoins, active: item.active, sortOrder: item.sortOrder } : initial);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const queryClient = useQueryClient();
  const update = <K extends keyof AchievementInput>(key: K, value: AchievementInput[K]) => setForm(f => ({ ...f, [key]: value }));
  const save = useMutation({ mutationFn: (body: AchievementInput) => api(item ? `/admin/achievements/${item.id}` : "/admin/achievements", { method: item ? "PUT" : "POST", body }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["admin", "achievements"] }); toast.success(item ? "Conquista atualizada" : "Conquista criada"); onClose(); } });
  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    const parsed = achievementInputSchema.safeParse(form);
    if (!parsed.success) { setErrors(Object.fromEntries(parsed.error.issues.map(issue => [issue.path.join("."), issue.message]))); return; }
    setErrors({}); save.mutate(parsed.data);
  };
  return <Drawer open onClose={() => !save.isPending && onClose()} title={item ? "Editar conquista" : "Criar conquista"} width="max-w-2xl" footer={<><Button variant="outline" disabled={save.isPending} onClick={onClose}>Cancelar</Button><Button type="submit" form="achievement-form" loading={save.isPending}><Check className="size-4" />{item ? "Salvar alterações" : "Criar conquista"}</Button></>}>
    <form id="achievement-form" onSubmit={submit} className="space-y-6">
      <div className="flex items-center gap-5 rounded-2xl bg-card p-5"><Medal achievement={form} large /><div className="min-w-0"><p className="text-xs font-semibold text-muted">Prévia no aplicativo</p><h3 className="mt-1 break-words font-display text-xl font-bold">{form.title || "Uma nova conquista"}</h3><p className="mt-1 break-words text-sm text-ink-2">{form.description || "Escreva um convite que dê vontade de começar."}</p><div className="mt-3 flex flex-wrap gap-2"><Badge>{difficulties[form.difficulty]}</Badge><Badge tone="brand">{number(form.xp)} XP</Badge>{form.bonusCoins > 0 && <Badge tone="citrus">+{number(form.bonusCoins)} moedas</Badge>}</div></div></div>
      <section className="space-y-4"><h3 className="font-display text-base font-bold">O convite ao cliente</h3>
        <Input label="Nome da conquista" autoFocus required minLength={3} maxLength={80} value={form.title} error={errors.title} placeholder="O começo de uma boa história" onChange={e => { const title = e.target.value; setForm(f => ({ ...f, title, ...(!item ? { slug: title.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") } : {}) })); }} />
        <Textarea label="Descrição para o cliente" required minLength={10} maxLength={350} rows={3} value={form.description} error={errors.description} placeholder="Receba sua primeira compra e comece sua coleção de conquistas." onChange={e => update("description", e.target.value)} />
        <div className="grid gap-4 sm:grid-cols-2"><Select label="Coleção" value={form.category} onChange={e => update("category", e.target.value as AchievementInput["category"])}>{Object.entries(categories).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</Select><Select label="Dificuldade" value={form.difficulty} onChange={e => update("difficulty", e.target.value as AchievementInput["difficulty"])}>{Object.entries(difficulties).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</Select></div>
        <fieldset><legend className="mb-2 text-xs font-semibold text-ink-2">Símbolo da medalha</legend><div className="flex flex-wrap gap-2">{Object.entries(icons).map(([key, Icon]) => <button key={key} type="button" aria-label={iconNames[key as keyof typeof icons]} title={iconNames[key as keyof typeof icons]} aria-pressed={form.icon === key} onClick={() => update("icon", key as AchievementInput["icon"])} className={`grid size-10 place-items-center rounded-xl ring-1 focus-visible:outline-2 focus-visible:outline-brand ${form.icon === key ? "bg-brand-soft text-brand ring-brand" : "bg-card text-ink-2 ring-line hover:bg-line-2"}`}><Icon className="size-5" /></button>)}</div></fieldset>
        <Select label="Cor da medalha" value={form.color} onChange={e => update("color", e.target.value as AchievementInput["color"])}>{Object.entries(colors).map(([value, color]) => <option key={value} value={value}>{color.name}</option>)}</Select>
      </section>
      <section className="space-y-4 border-t border-line pt-6"><h3 className="font-display text-base font-bold">Como a conquista é liberada</h3><Select label="Ação acompanhada" value={form.rule.metric} error={errors["rule.metric"]} onChange={e => { const metric = e.target.value as AchievementMetric; setForm(f => ({ ...f, rule: { metric, target: isMoney(metric) ? 10000 : 1 } })); }}>{achievementMetrics.map(metric => <option key={metric} value={metric}>{metrics[metric].label}</option>)}</Select>
        <p className="text-sm leading-relaxed text-ink-2">{metrics[form.rule.metric].help}</p>
        <Input label="Meta para concluir" type="number" min={isMoney(form.rule.metric) ? 0.01 : 1} max={isMoney(form.rule.metric) ? 1000000 : 100000000} step={isMoney(form.rule.metric) ? "0.01" : 1} required disabled={form.rule.metric === "profile_complete"} prefix={isMoney(form.rule.metric) ? "R$" : undefined} suffix={!isMoney(form.rule.metric) ? metrics[form.rule.metric].unit : undefined} value={isMoney(form.rule.metric) ? form.rule.target / 100 : form.rule.target} error={errors["rule.target"]} onChange={e => update("rule", { ...form.rule, target: isMoney(form.rule.metric) ? Math.round(Number(e.target.value) * 100) : Number(e.target.value) })} />
        <p className="text-xs leading-relaxed text-muted">O progresso é calculado automaticamente a partir do histórico válido do cliente. Cada conquista só pode ser recebida uma vez.</p>
      </section>
      <section className="space-y-4 border-t border-line pt-6"><h3 className="font-display text-base font-bold">Reconhecimento e recompensa</h3><div className="grid gap-4 sm:grid-cols-2"><Input label="Experiência (XP)" type="number" min={0} max={10000} required value={form.xp} error={errors.xp} onChange={e => update("xp", Number(e.target.value))} /><Input label="Moedas de bônus" type="number" min={0} max={100000} required value={form.bonusCoins} error={errors.bonusCoins} onChange={e => update("bonusCoins", Number(e.target.value))} /></div><p className="text-sm leading-relaxed text-ink-2">XP aumenta o nível do cliente. Moedas entram no saldo de fidelidade e podem ser trocadas por prêmios. Use zero para oferecer apenas a medalha.</p>{item && <p className="rounded-xl bg-citrus-soft p-3 text-sm text-amber-900">Alterações valem para novas conquistas. Quem já recebeu mantém a medalha e a recompensa originais.</p>}</section>
      <section className="space-y-4 border-t border-line pt-6"><h3 className="font-display text-base font-bold">Publicação</h3><Switch checked={form.active} onChange={value => update("active", value)} label="Ativa no aplicativo" /><div className="grid gap-4 sm:grid-cols-2"><Input label="Posição na coleção" type="number" min={0} max={100000} required value={form.sortOrder} error={errors.sortOrder} onChange={e => update("sortOrder", Number(e.target.value))} hint="Números menores aparecem primeiro." /><Input label="Identificador" required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug} error={errors.slug} onChange={e => update("slug", e.target.value)} hint="Único, sem espaços ou acentos." /></div></section>
      {Object.keys(errors).length > 0 && <p role="alert" className="text-sm text-sale">Revise os campos destacados antes de salvar.</p>}{save.error && <p role="alert" className="rounded-xl bg-sale-soft p-3 text-sm text-sale">Não foi possível salvar: {save.error.message}. Revise os dados e tente novamente.</p>}
    </form>
  </Drawer>;
}

function Recipients({ item, onClose }: { item: Achievement; onClose: () => void }) {
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const result = useQuery({ queryKey: ["admin", "achievements", item.id, "recipients", search, page], queryFn: ({ signal }) => api<AchievementRecipients>(`/admin/achievements/${item.id}/recipients${qs({ search, page, pageSize: 15 })}`, { signal }) });
  return <Drawer open onClose={onClose} title={`Quem conquistou: ${item.title}`} width="max-w-2xl"><div className="mb-5 flex gap-3"><Medal achievement={item} /><div><p className="font-semibold">{result.data ? `${number(result.data.total)} clientes conquistaram` : "Clientes que chegaram lá"}</p><p className="text-sm text-muted">Medalhas e recompensas preservadas na data da conquista.</p></div></div><Input label="Buscar cliente" placeholder="Nome ou e-mail" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} />
    {result.isPending ? <div className="mt-5 space-y-3">{[1, 2, 3].map(i => <Skeleton key={i} className="h-16" />)}</div> : result.error ? <div role="alert" className="py-8 text-sm text-sale">Não foi possível carregar os clientes. <Button variant="outline" onClick={() => void result.refetch()}>Tentar novamente</Button></div> : !result.data?.items.length ? <EmptyState icon={<Users />} title={search ? "Nenhum cliente encontrado" : "A primeira medalha está a caminho"} description={search ? "Tente outro nome ou e-mail." : "Os clientes aparecerão aqui assim que concluírem esta conquista."} /> : <><ul className="mt-5 divide-y divide-line">{result.data.items.map(recipient => <li key={recipient.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="break-words font-semibold">{recipient.name}</p><p className="break-all text-sm text-muted">{recipient.email}</p><p className="mt-1 text-xs text-muted">{new Date(recipient.awardedAt).toLocaleString("pt-BR")}</p></div><div className="flex gap-2"><Badge tone="brand">{number(recipient.snapshot.xp)} XP</Badge>{recipient.snapshot.bonusCoins > 0 && <Badge tone="citrus">+{number(recipient.snapshot.bonusCoins)} moedas</Badge>}</div></li>)}</ul><div className="mt-5 flex items-center justify-between gap-2"><p className="text-sm text-muted">Página {page} de {Math.max(1, Math.ceil(result.data.total / 15))}</p><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Página anterior" disabled={page === 1} onClick={() => setPage(p => p - 1)}><ChevronLeft className="size-4" /></Button><Button variant="outline" size="icon" aria-label="Próxima página" disabled={page * 15 >= result.data.total} onClick={() => setPage(p => p + 1)}><ChevronRight className="size-4" /></Button></div></div></>}
  </Drawer>;
}

export function AchievementsScreen() {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["admin", "achievements"], queryFn: ({ signal }) => api<AdminAchievements>("/admin/achievements", { signal }) });
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [status, setStatus] = useState(""); const [difficulty, setDifficulty] = useState("");
  const [editor, setEditor] = useState<Achievement | "new" | null>(null); const [recipients, setRecipients] = useState<Achievement | null>(null); const [archive, setArchive] = useState<Achievement | null>(null);
  const archiveMutation = useMutation({ mutationFn: (id: string) => api(`/admin/achievements/${id}/archive`, { method: "POST" }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["admin", "achievements"] }); toast.success("Conquista desativada. O histórico foi preservado."); setArchive(null); }, onError: error => toast.error(error.message) });
  const normalized = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const items = query.data?.achievements.filter(item => (!search || normalized(`${item.title} ${item.description}`).includes(normalized(search))) && (!category || item.category === category) && (!difficulty || item.difficulty === difficulty) && (!status || item.active === (status === "active"))).sort((a, b) => a.sortOrder - b.sortOrder) ?? [];
  const clear = () => { setSearch(""); setCategory(""); setStatus(""); setDifficulty(""); };
  return <>
    <PageHeader title="Conquistas" description="Transforme pequenos momentos em motivos para voltar." actions={<Button onClick={() => setEditor("new")}><Plus className="size-4" />Criar conquista</Button>} />
    <section className="mb-6 rounded-2xl bg-brand-soft px-5 py-5 sm:px-6"><div className="flex items-start gap-4"><Trophy className="mt-1 size-7 shrink-0 text-brand" /><div><h2 className="font-display text-lg font-bold text-brand">Uma jornada que reconhece cada cliente</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-brand">Misture primeiros passos, descobertas e desafios de longo prazo. Cada medalha tem sua própria meta, dificuldade e recompensa.</p></div></div>{query.data && <dl className="mt-5 flex flex-wrap gap-x-8 gap-y-3 border-t border-brand/15 pt-4 text-sm text-brand">{[["ativas", query.data.stats.active], ["medalhas entregues", query.data.stats.awards], ["clientes premiados", query.data.stats.participants], ["moedas de bônus entregues", query.data.stats.bonusCoins]].map(([label, value]) => <div key={label} className="flex gap-1.5"><dd className="font-bold tabular-nums">{number(Number(value))}</dd><dt>{label}</dt></div>)}</dl>}</section>
    <div className="mb-5 grid items-end gap-3 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_180px_170px_150px]"><Input label="Buscar conquista" placeholder="Nome ou descrição" value={search} onChange={e => setSearch(e.target.value)} /><Select label="Coleção" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas as coleções</option>{Object.entries(categories).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</Select><Select label="Dificuldade" value={difficulty} onChange={e => setDifficulty(e.target.value)}><option value="">Todas</option>{Object.entries(difficulties).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</Select><Select label="Publicação" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todas</option><option value="active">Ativas</option><option value="inactive">Inativas</option></Select></div>
    {(search || category || status || difficulty) && <div className="mb-3 flex items-center justify-between"><p className="text-sm text-muted">{items.length} conquistas encontradas</p><Button variant="ghost" size="sm" onClick={clear}><X className="size-3.5" />Limpar filtros</Button></div>}
    {query.isPending ? <div aria-label="Carregando conquistas" className="space-y-3">{[1, 2, 3, 4].map(i => <Skeleton key={i} className="h-28" />)}</div> : query.error ? <div role="alert" className="rounded-2xl bg-sale-soft p-6"><p className="mb-3 text-sale">Não foi possível carregar as conquistas. {query.error.message}</p><Button variant="outline" onClick={() => void query.refetch()}>Tentar novamente</Button></div> : items.length === 0 ? <EmptyState icon={<Trophy />} title={query.data?.achievements.length ? "Nenhuma conquista com esses filtros" : "Sua coleção começa aqui"} description={query.data?.achievements.length ? "Experimente outra busca ou limpe os filtros." : "Crie um primeiro desafio simples para dar as boas-vindas aos clientes."} action={<Button onClick={query.data?.achievements.length ? clear : () => setEditor("new")}>{query.data?.achievements.length ? "Limpar filtros" : "Criar primeira conquista"}</Button>} /> : <div className="overflow-hidden rounded-2xl border border-line bg-card"><ul className="divide-y divide-line">{items.map(item => <li key={item.id} className="flex flex-wrap items-start gap-4 p-5 transition-colors hover:bg-line-2/40 sm:flex-nowrap"><Medal achievement={item} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-base font-bold">{item.title}</h3><Badge tone={item.active ? "brand" : "neutral"}>{item.active ? "Ativa" : "Inativa"}</Badge></div><p className="mt-1 max-w-2xl break-words text-sm text-ink-2">{item.description}</p><p className="mt-2 text-xs font-medium text-muted">{ruleLabel(item)}</p><div className="mt-3 flex flex-wrap items-center gap-2"><Badge>{categories[item.category]}</Badge><Badge tone={item.difficulty === "legendary" ? "club" : "neutral"}>{difficulties[item.difficulty]}</Badge><span className="text-xs font-semibold text-brand">{number(item.xp)} XP</span>{item.bonusCoins > 0 && <span className="text-xs font-semibold text-amber-800">+{number(item.bonusCoins)} moedas</span>}</div></div><div className="flex w-full flex-wrap items-center justify-end gap-1 sm:w-auto sm:max-w-44"><Button variant="ghost" size="sm" onClick={() => setRecipients(item)} aria-label={`Ver clientes que conquistaram ${item.title}`}><Users className="size-4" />{number(item.recipientsCount)} clientes</Button><Button variant="outline" size="sm" onClick={() => setEditor(item)}><Pencil className="size-3.5" />Editar</Button>{item.active && <Button variant="ghost" size="icon" onClick={() => setArchive(item)} aria-label={`Desativar ${item.title}`} title="Desativar conquista"><Archive className="size-4" /></Button>}</div></li>)}</ul></div>}
    <p className="mt-5 max-w-3xl text-xs leading-relaxed text-muted">Conquistas inativas deixam de receber novas liberações. O histórico de quem já conquistou e suas recompensas permanecem preservados.</p>
    {editor && <AchievementEditor item={editor === "new" ? null : editor} onClose={() => setEditor(null)} />}{recipients && <Recipients item={recipients} onClose={() => setRecipients(null)} />}
    <ConfirmDialog open={!!archive} onClose={() => !archiveMutation.isPending && setArchive(null)} onConfirm={() => archive && archiveMutation.mutate(archive.id)} title="Desativar esta conquista?" description={`“${archive?.title ?? ""}” deixará de liberar novas medalhas. Clientes que já conquistaram manterão seu histórico e suas recompensas. Você poderá reativá-la em Editar.`} confirmLabel="Desativar conquista" loading={archiveMutation.isPending} />
  </>;
}


